/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:72129014-5988-40b8-b2ad-c8a9c57a9f2a",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_ZrjMSm2x8",
    "aws_user_pools_web_client_id": "4kob0fpip2l7afbdups4m0scs6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cwtwqwiu25dvxcpb6qckhd623y.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wi354gayvngydfs4d2tat5bjai"
};


export default awsmobile;
