/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:0c591346-f39d-4f5b-b959-0a9c0c371d8a",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_r1O9a1mH9",
    "aws_user_pools_web_client_id": "51m0rfokmjb7ch5pr2go0mlshe",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cwtwqwiu25dvxcpb6qckhd623y.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wi354gayvngydfs4d2tat5bjai"
};


export default awsmobile;
